import { Router } from 'express';
import crypto from 'crypto';
import { spotifyService } from '../services/spotify';

export const spotifyRouter = Router();
const pkceStore = new Map<string, string>();

function generateCodeVerifier(): string {
  return crypto.randomBytes(32).toString('base64url');
}

function generateCodeChallenge(verifier: string): string {
  return crypto.createHash('sha256').update(verifier).digest('base64url');
}

spotifyRouter.get('/auth-url', (req, res) => {
  const state = crypto.randomBytes(16).toString('hex');
  const codeVerifier = generateCodeVerifier();
  const codeChallenge = generateCodeChallenge(codeVerifier);
  pkceStore.set(state, codeVerifier);
  res.json({
    authUrl: spotifyService.getAuthorizationUrl(state, codeChallenge),
    state,
  });
});

spotifyRouter.post('/exchange', async (req, res) => {
  const { code, state } = req.body;
  if (!code || !state) {
    return res.status(400).json({ error: 'Missing code or state' });
  }
  const codeVerifier = pkceStore.get(state);
  if (!codeVerifier) {
    return res.status(400).json({ error: 'Invalid or expired state' });
  }
  try {
    const tokens = await spotifyService.exchangeCodeForTokens(code, codeVerifier);
    pkceStore.delete(state);
    res.json(tokens);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Exchange failed';
    res.status(400).json({ error: message });
  }
});

spotifyRouter.post('/refresh', async (req, res) => {
  const { refresh_token } = req.body;
  if (!refresh_token) {
    return res.status(400).json({ error: 'Missing refresh_token' });
  }
  try {
    const tokens = await spotifyService.refreshAccessToken(refresh_token);
    res.json(tokens);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Refresh failed';
    res.status(400).json({ error: message });
  }
});

spotifyRouter.get('/me', async (req, res) => {
  const auth = req.headers.authorization;
  if (!auth?.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing or invalid Authorization header' });
  }
  const accessToken = auth.slice(7);
  try {
    const profile = await spotifyService.getCurrentUserProfile(accessToken);
    res.json(profile);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Failed to fetch profile';
    res.status(400).json({ error: message });
  }
});

spotifyRouter.get('/genres', async (req, res) => {
  const auth = req.headers.authorization;
  if (!auth?.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing or invalid Authorization header' });
  }
  const accessToken = auth.slice(7);
  try {
    const genres = await spotifyService.getGenreSeeds(accessToken);
    res.json({ genres });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Failed to fetch genres';
    res.status(400).json({ error: message });
  }
});

spotifyRouter.post('/create-playlist', async (req, res) => {
  const auth = req.headers.authorization;
  if (!auth?.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing or invalid Authorization header' });
  }
  const accessToken = auth.slice(7);
  const {
    name,
    description,
    seed_genres,
    seed_artists,
    seed_tracks,
    target_valence,
    target_energy,
    target_acousticness,
  } = req.body;

  if (!name) {
    return res.status(400).json({ error: 'Playlist name required' });
  }

  const hasSeeds = (seed_genres?.length || seed_artists?.length || seed_tracks?.length) > 0;
  if (!hasSeeds) {
    return res.status(400).json({ error: 'At least one seed (genres, artists, or tracks) required' });
  }

  try {
    const user = await spotifyService.getCurrentUser(accessToken);
    const genres = seed_genres || [];
    let tracks;
    if (genres.length > 0) {
      tracks = await spotifyService.searchTracksByGenres(accessToken, genres, 50);
    } else {
      try {
        tracks = await spotifyService.getRecommendations(accessToken, {
          seed_genres: [],
          seed_artists: seed_artists || [],
          seed_tracks: seed_tracks || [],
          target_valence,
          target_energy,
          target_acousticness,
          limit: 50,
        });
      } catch {
        tracks = await spotifyService.searchTracksByGenres(accessToken, ['ambient', 'chill', 'indie'], 50);
      }
    }

    if (tracks.length === 0) {
      return res.status(400).json({ error: 'No tracks found. Try different seeds or add genre seeds.' });
    }

    const playlist = await spotifyService.createPlaylist(
      accessToken,
      user.id,
      name,
      description || 'Generated by Vibe Playlist'
    );
    await spotifyService.addTracksToPlaylist(
      accessToken,
      playlist.id,
      tracks.map((t) => t.uri)
    );
    res.json({
      playlist: {
        id: playlist.id,
        uri: playlist.uri,
        href: playlist.href,
      },
      tracksAdded: tracks.length,
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Failed to create playlist';
    res.status(400).json({ error: message });
  }
});
